name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/master'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.155.1/hugo_extended_0.155.1_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo

      # - name: Build local ./exampleSite
      #   run: hugo --minify --gc --destination ../public --source ./exampleSite --themesDir ../../ --baseURL https://happyhomehappyheart.github.io/

      - name: Build
        run: ${RUNNER_TEMP}/hugo

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'kymahi'
          git config user.email 'hentercenter@gmail.com'
          git commit -m 'Updated site'
          git push

      # - name: Deploy to GitHub Pages
      #   if: github.event_name == 'push'
      #   uses: peaceiris/actions-gh-pages@v4.0.0
      #   with:
      #     github_token: ${{ secrets.PERSONAL_TOKEN }}
      #     publish_branch: gh-pages
      #     publish_dir: ./public
